[package]
name = "polkadot-voter-bags"
version = "0.9.31"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }

generate-bags = { git = "https://github.com/paritytech/substrate", branch = "tsv-unknown-block" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "tsv-unknown-block" }

westend-runtime = { path = "../../runtime/westend" }
kusama-runtime = { path = "../../runtime/kusama" }
polkadot-runtime = { path = "../../runtime/polkadot" }
